# Generated by Django 2.2.5 on 2019-09-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('icon', models.ImageField(upload_to='images/')),
                ('icon1', models.ImageField(upload_to='images/')),
                ('icon2', models.ImageField(upload_to='images/')),
                ('icon3', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('icon', models.ImageField(upload_to='images/')),
                ('icon1', models.ImageField(upload_to='images/')),
                ('icon2', models.ImageField(upload_to='images/')),
                ('icon3', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
